# SPDX-FileCopyrightText: (c) 2025 Tenstorrent AI ULC
# SPDX-License-Identifier: Apache-2.0

"""
ruleset.py — FreeCiv ruleset writer for TT-generated civilizations
====================================================================

Writes FreeCiv .ruleset INI files for custom civilizations whose parameters
were generated on P300C Blackhole hardware.

FreeCiv nation definition (nations/<slug>.ruleset):
  - Leader names
  - Nation description
  - City list
  - Flag file reference
  - Ethnicity / language group (controls AI name style)
  - Preferred government/religion (optional)

We also write:
  - A nations.ruleset index file listing all custom nations
  - A patch script that adds our nations to the active ruleset
  - A colors.spec patch for unit/city colors

Genome parameters mapped to ruleset settings:
  [0]  aggression      → ai_style: aggressiveness
  [1]  expansion       → ai_style: expansionism
  [2]  science_focus   → ai_style: science
  [3]  trade_focus     → ai_style: trade
  [4]  military_focus  → ai_style: military
  [6]  naval_focus     → ai_style: naval
  [7]  terrain_pref    → preferred_tileset_group (flavor only)
  [40] start_era_bias  → preferred_start_advances (not in ruleset; for reference)
"""

from pathlib import Path
import math

import torch


# ── AI personality scaling ────────────────────────────────────────────────────

def _genome_to_ai_style(genome: torch.Tensor) -> dict:
    """
    Map genome parameters to FreeCiv AI style values (0-100 each).

    FreeCiv AI style fields (all optional, all 0-100):
      - expansionism : how eagerly the AI settles new territory
      - trade        : how much the AI prioritizes commerce
      - military     : how much the AI builds military units
      - science      : how eagerly the AI researches technology
    """
    def scale(v: float) -> int:
        return max(0, min(100, int(v * 100)))

    return {
        "expansionism": scale(genome[1].item()),
        "trade":        scale(genome[3].item()),
        "military":     scale(genome[4].item()),
        "science":      scale(genome[2].item()),
    }


# ── FreeCiv unit stat bonuses ─────────────────────────────────────────────────
# These are written as "effect" entries — they modify the base ruleset.
# FreeCiv effects use: type, value, reqs (list of conditions)

def _genome_to_unit_biases(genome: torch.Tensor) -> dict:
    """
    Map genome unit bias parameters to bonus values.

    FreeCiv treats unit stats as base values from the unit's ruleset entry.
    We can't easily override per-unit stats without rewriting the entire
    units.ruleset, so instead we express these as small country-wide effects.

    Returns a dict with 'attack', 'defense', 'movement', 'hp' bias values
    in the range ±10 to be logged/displayed (not currently applied to ruleset
    as that requires full ruleset rewrite).
    """
    def bias(v: float) -> int:
        # Map [0, 1] → [-5, +5] bonus
        return int((v - 0.5) * 10)

    return {
        "attack":   bias(genome[12].item()),
        "defense":  bias(genome[13].item()),
        "movement": bias(genome[14].item()),
        "hp":       bias(genome[15].item()),
    }


# ── Ruleset file templates ────────────────────────────────────────────────────

_NATION_RULESET_TEMPLATE = """\
; Auto-generated by civgen/ruleset.py
; TT-Lang P300C Blackhole hardware-generated civilization
; (c) 2025 Tenstorrent AI ULC

[nation_{slug}]

name          = _("{nation}")
plural        = _("{nation_plural}")
groups        = "TT-Generated"
legend        = _("The {adjective} people, forged by Blackhole hardware.")

leaders = {{
  {leader_entries}
}}

flag         = "{slug}"
flag_alt     = "-"

; AI style (0-100 scale) — values from TT genome
; Expansionism: {expansionism}  Trade: {trade}  Military: {military}  Science: {science}

city_style = "{city_style}"

cities =
  "{city1}",
  "{city2}",
  "{city3}",
  ; (TT hardware generated the phoneme matrices for all these names)
"""

# Mapping from terrain_pref genome param to FreeCiv city style
# FreeCiv has: European, Classical, Tropical, Asian, Babylonian, Celtic
_TERRAIN_CITY_STYLES = [
    "European",     # 0: plains
    "European",     # 1: grassland
    "Celtic",       # 2: forest
    "Babylonian",   # 3: tundra
    "Classical",    # 4: desert
    "European",     # 5: coastal
    "Babylonian",   # 6: mountains
    "Tropical",     # 7: swamp
]

_NATIONS_RULESET_HEADER = """\
; nations.ruleset — TT-Generated custom nations index
; Auto-generated by civgen/ruleset.py
; (c) 2025 Tenstorrent AI ULC

[datafile]
description = "TT-Lang P300C hardware-generated civilizations"
options = "+Freeciv-ruleset-Devel-2023-Feb-13 nations"

; Include all generated nation files
*include "nations/default_nations.ruleset"

"""


def write_nation_ruleset(
    genome: torch.Tensor,
    names: dict,
    slug: str,
    output_dir: Path,
) -> Path:
    """
    Write a single nation's .ruleset file.

    Parameters
    ----------
    genome     : (64,) float32 genome for this civ
    names      : name dict from name_gen.generate_names() for this civ
    slug       : lowercase slug (e.g. "romai")
    output_dir : output directory (will write to output_dir/nations/<slug>.ruleset)

    Returns
    -------
    Path to the written .ruleset file
    """
    nations_dir = output_dir / "nations"
    nations_dir.mkdir(parents=True, exist_ok=True)

    ai_style    = _genome_to_ai_style(genome)
    unit_biases = _genome_to_unit_biases(genome)

    terrain_pref  = int(genome[7].item() * 7.99)
    city_style    = _TERRAIN_CITY_STYLES[terrain_pref]

    # Leader entry: one leader with M or F gender, name from names dict
    # Genome value > 0.5 → male leader in portrait (use M gender marker)
    gender = "Male" if genome[29].item() < 0.5 else "Female"
    leader_entries = f'{{ "name" = _("{names["leader"]}"), "sex" = "{gender}" }}'

    content = _NATION_RULESET_TEMPLATE.format(
        slug          = slug,
        nation        = names["nation"],
        nation_plural = names["nation"] + "s",
        adjective     = names["adjective"],
        leader_entries = leader_entries,
        expansionism  = ai_style["expansionism"],
        trade         = ai_style["trade"],
        military      = ai_style["military"],
        science       = ai_style["science"],
        city_style    = city_style,
        city1         = names["city1"],
        city2         = names["city2"],
        city3         = names["city3"],
    )

    out_path = nations_dir / f"{slug}.ruleset"
    out_path.write_text(content)
    return out_path


def write_nations_index(
    slugs: list[str],
    names_list: list[dict],
    output_dir: Path,
) -> Path:
    """
    Write the nations.ruleset index file that *include's all custom nations.

    Parameters
    ----------
    slugs      : list of slug strings
    names_list : list of name dicts (one per civ, from name_gen)
    output_dir : output directory

    Returns
    -------
    Path to the written nations.ruleset
    """
    lines = [_NATIONS_RULESET_HEADER]

    for slug in slugs:
        lines.append(f'*include "nations/{slug}.ruleset"')
        lines.append("")

    out_path = output_dir / "nations.ruleset"
    out_path.write_text("\n".join(lines))
    return out_path


def write_nation_summary(
    genomes: torch.Tensor,
    names_list: list[dict],
    slugs: list[str],
    output_dir: Path,
) -> Path:
    """
    Write a human-readable summary of all generated civilizations.

    This is a plain-text file showing every genome parameter alongside
    the generated values — useful for debugging and demo presentation.

    Parameters
    ----------
    genomes    : (n_civs, 64) float32 tensor
    names_list : list of name dicts
    slugs      : list of slugs
    output_dir : output directory

    Returns
    -------
    Path to the written summary file
    """
    lines = [
        "=" * 70,
        "TT-Lang P300C Blackhole Generated Civilizations",
        "=" * 70,
        "",
    ]

    PARAM_NAMES = [
        "aggression", "expansion", "science_focus", "trade_focus",
        "military_focus", "culture_focus", "naval_focus", "terrain_pref",
        "city_growth", "production_bonus", "research_bonus", "happiness_focus",
        "unit_attack_bias", "unit_defense_bias", "unit_move_bias", "unit_hp_bias",
        "color_hue", "color_sat", "color_val",
        "color2_hue", "color2_sat", "color2_val",
        "flag_pattern", "flag_emblem", "flag_complexity",
        "phoneme_vowel", "phoneme_hard", "phoneme_length", "phoneme_syllables",
        "portrait_skin", "portrait_hair", "portrait_face", "portrait_expr",
        "portrait_headgear", "portrait_garment", "portrait_beard",
        "ai_trait_settle", "ai_trait_wonder", "ai_trait_gold", "ai_trait_tech",
        "start_era_bias", "wonder_affinity",
    ]

    for i, (slug, names) in enumerate(zip(slugs, names_list)):
        genome   = genomes[i]
        ai_style = _genome_to_ai_style(genome)
        biases   = _genome_to_unit_biases(genome)

        lines += [
            f"── Civilization {i+1}: {names['nation']} ──",
            f"   Leader    : {names['leader']}",
            f"   Slug      : {slug}",
            f"   Nation    : {names['nation']} (adj: {names['adjective']})",
            f"   Cities    : {names['city1']}, {names['city2']}, {names['city3']}",
            "",
            f"   AI Style:",
            f"     Expansion  {ai_style['expansionism']:3d}/100",
            f"     Trade      {ai_style['trade']:3d}/100",
            f"     Military   {ai_style['military']:3d}/100",
            f"     Science    {ai_style['science']:3d}/100",
            "",
            f"   Unit Biases (vs baseline):",
            f"     Attack    {biases['attack']:+d}",
            f"     Defense   {biases['defense']:+d}",
            f"     Movement  {biases['movement']:+d}",
            f"     HP        {biases['hp']:+d}",
            "",
            "   Genome (selected parameters):",
        ]

        for j, name in enumerate(PARAM_NAMES[:16]):
            val = genome[j].item()
            lines.append(f"     [{j:2d}] {name:<22} = {val:.3f}")

        lines.append("")

    out_path = output_dir / "civilization_summary.txt"
    out_path.write_text("\n".join(lines) + "\n")
    return out_path


def write_all_rulesets(
    genomes: torch.Tensor,
    names_list: list[dict],
    slugs: list[str],
    output_dir: Path,
) -> dict[str, Path]:
    """
    Write all ruleset files for all civilizations.

    Parameters
    ----------
    genomes    : (n_civs, 64) float32 tensor from TT hardware
    names_list : list of name dicts from name_gen.generate_names()
    slugs      : list of slug strings
    output_dir : base output directory

    Returns
    -------
    dict with keys:
      "nations_index" → Path to nations.ruleset
      "summary"       → Path to civilization_summary.txt
      "nation_files"  → list of Paths to individual nation ruleset files
    """
    nation_files = []
    for i, (slug, names) in enumerate(zip(slugs, names_list)):
        path = write_nation_ruleset(genomes[i], names, slug, output_dir)
        nation_files.append(path)

    index_path   = write_nations_index(slugs, names_list, output_dir)
    summary_path = write_nation_summary(genomes, names_list, slugs, output_dir)

    return {
        "nations_index": index_path,
        "summary":       summary_path,
        "nation_files":  nation_files,
    }


# ── Standalone test ──────────────────────────────────────────────────────────

if __name__ == "__main__":
    import sys
    sys.path.insert(0, "..")
    from kernels.civ_genome import generate_genomes_hardware, generate_phoneme_matrices_hardware
    from civgen.name_gen import generate_names
    import ttnn
    from pathlib import Path

    N = 6
    SEED = 42

    print("=" * 60)
    print("Ruleset Writer — Hardware Test")
    print(f"Generating {N} civilization rulesets (seed={SEED})")
    print("=" * 60)

    device = ttnn.open_device(device_id=0)
    try:
        genomes, g_ms  = generate_genomes_hardware(N, SEED, device)
        matrices, p_ms = generate_phoneme_matrices_hardware(genomes, SEED, device)
    finally:
        ttnn.close_device(device)

    print(f"TT kernel time: {g_ms + p_ms:.3f}ms")

    names_list = generate_names(genomes, matrices, SEED)
    slugs      = [n["nation"].lower().replace(" ", "_")[:10] for n in names_list]

    out   = Path("output/civtest")
    paths = write_all_rulesets(genomes, names_list, slugs, out)

    print(f"\nNations index: {paths['nations_index']}")
    print(f"Summary:       {paths['summary']}")
    print("\nNation files:")
    for p in paths["nation_files"]:
        print(f"  {p}")

    # Print the summary
    print("\n" + paths["summary"].read_text()[:1000])
